spring:
  application:
    name: zipkin-server
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  sleuth:
    sampler:
      probability: 1.0
    enabled: true
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    compression:
      enabled: true

server:
  port: 8081

zipkin:
  storage:
      type: mysql

